In [ ]:
from google.colab import drive
drive.mount("/gdrive", force_remount=True)

Mounted at /gdrive


In [ ]:
import numpy as np
import torch
import torch.nn as nn
from sklearn.metrics import accuracy_score

# 데이터 읽기 함수
def load_dataset(file):
  data = np.loadtxt(file)
  print("DATA=",data)
  
  input_features = data[:,0:-1]
  print("X=",input_features)
  
  labels = np.reshape(data[:,-1],(4,1))
  print("Y=",labels)
 
  input_features = torch.tensor(input_features, dtype=torch.float)
  labels = torch.tensor(labels, dtype=torch.float)

  return (input_features, labels)

# 모델 평가 결과 계산을 위해 텐서를 리스트로 변환하는 함수
def tensor2list(input_tensor):
    return input_tensor.cpu().detach().numpy().tolist()

x, y = load_dataset("/gdrive/My Drive/colab/ann/xor1/train.txt")

# layer 1 가중치 초기화
w1 = torch.randn(2,2, requires_grad=True)
b1 = torch.randn(2, requires_grad=True)

print("\n[Init]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))

# layer 2 가중치 초기화
w2 = torch.randn(2,1, requires_grad=True)
b2 = torch.randn(1, requires_grad=True)

print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))

# Activation 함수 설정
sigmoid = nn.Sigmoid()

# 이진분류 크로스엔트로피 비용 함수 설정 
loss_func = torch.nn.BCELoss()

# 옵티마이저 함수 (역전파 알고리즘을 수행할 함수)
optimizer = torch.optim.SGD([w1,b1,w2,b2],lr=0.2)

# 모델 학습
for epoch in range(1001):

    # H(X) 계산: forward 연산
    L2 = sigmoid(torch.add(torch.matmul(x,w1), b1))
    hx = sigmoid(torch.add(torch.matmul(L2,w2), b2))
    # 비용 계산
    cost = loss_func(hx, y)
    # 역전파 수행
    cost.backward()
    optimizer.step()

    # 100 에폭마다 비용 출력
    if epoch % 100 == 0:
        print(epoch, cost.item())

print("\n[Learned]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))
print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))

# 모델 평가
# H(X) 계산: forward 연산
logits = (hx > 0.5).float()
predicts = tensor2list(logits)
golds = tensor2list(y)

print("\nPRED=",predicts)
print("GOLD=",golds)
print("Accuracy : {0:f}".format(accuracy_score(golds, predicts)))

DATA= [[0. 0. 0.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
X= [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Y= [[0.]
 [1.]
 [1.]
 [0.]]

[Init]
w1 = [[0.6805678009986877, 0.07648158818483353], [-0.14783184230327606, 1.9188761711120605]]
b1 = [-0.9421648979187012, 0.23485133051872253]
w2 = [[0.3760331869125366], [0.40240421891212463]]
b2 = [-0.4977397322654724]

0 0.6934831738471985
100 0.3716077208518982
200 0.3466690182685852
300 0.34660184383392334
400 0.3465735912322998
500 0.34660273790359497
600 0.3466702699661255
700 0.3467324376106262
800 0.34674882888793945
900 0.3467089533805847
1000 0.346638560295105

[Learned]
w1 = [[33.02348327636719, 130.26168823242188], [-159.5340576171875, 173.3573455810547]]
b1 = [-14.622021675109863, -17.730106353759766]
w2 = [[128.59619140625], [128.5943145751953]]
b2 = [-128.572265625]


PRED= [[0.0], [1.0], [1.0], [1.0]]
GOLD= [[0.0], [1.0], [1.0], [0.0]]
Accuracy : 0.750000
